### ISSUE TITLE
Add an error message when --range is used with a '-'

### ISSUE THREAD

**Issue by mfe** [tuttleofx/TuttleOFX#136]
The right syntax is --range 10,15.
For now, if the user make a mistake like --range 10-15, nothing appends (no process and no error).

**Comment by cchampet** [comment]
I think we are talking about sam-do?

**Comment by cchampet** [comment]
Since the sam do in python, we currently accept only numbers.
--ranges 10 // process frame 10
--ranges 10 15 // process frames 10 to 15
--ranges 10 15 20 // process frames 10 to 15 and 20
--ranges 10 15 20  25 // process frames 10 to 15 and 20 to 25
And so on.
Need to accept dash or comma for each range.
