### ISSUE TITLE
FFmbcReader and FFmbcWriter

### ISSUE THREAD

**Issue by cbenhagen** [tuttleofx/TuttleOFX#201]
Please consider implementing FFmbc (FFmpeg customized for broadcast and professional usage) support.

--> https://code.google.com/p/ffmbc/

**Comment by cchampet** [comment]
Since AudioVideo v4.x, the plugin is not based on ffmpeg, but on [AvTranscoder](https://github.com/avTranscoder/avTranscoder). This library should be able to use both ffmpeg and ffmbc.  An issue exists on the [Mikros fork repository](https://github.com/mikrosimage/avTranscoder/issues/202). This task will be the next step. After that, no more question about the TuttleOFX plugin: it will be the same for both ffmpeg and ffmbc. Just need to propose TuttleOFX binaries with the following dependency link:
AudioVideo --> AvTranscoder --> ffmbc.

**Comment by MarcAntoine-Arnaud** [comment]
FFmbc is not maintened now. Last activity was very far... An the main developper has rejoins reccently the FFmpeg team.
If this it was a non sens to pass time to integrate this library now.

**Comment by cchampet** [comment]
You right, since several years ffmbc is not maintained, and its features has been reported to ffmpeg.
Currently, you have several profiles which can feet your needs @cbenhagen:
https://github.com/mikrosimage/avTranscoder/blob/develop/avprofiles/
