### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by Eiken** [tuttleofx/TuttleOFX#526]
Trying to get "sam" going. Maybe doing something terribly wrong but I am getting lots of errors about missing libraries. 

Couldn't open library because "libGLEW.so.1.6: cannot open shared object file: No such file or directory"
System contains /usr/lib64/libGLEW.so.1.10

Couldn't open library because "/lib64/libpng14.so.14: version `PNG14_0' not found
System contains /usr/lib64/libpng15.so.15

Couldn't open library because "libwebp.so.0: cannot open shared object file: 
libwebp.so.2 is in lib folder

Running CentOS 7. Do I need to compile tuttleofx from scratch to get it going?

**Comment by cchampet** [comment]
Hello,
You get the binaries from the last tag on github?
If so, it is possible that some plugins failed to load because of missing libraries (__libGLEW.so.1.6__ for the __viewer__ plugin, __libpng14.so.14__ for __png__ plugins, ...). Indeed the build is done for __ubuntu 12.04__, so running it on CentOS 7 may cause some problems. But the sam command line should work.

To run sam command line, you will need python and [2 python packages](https://github.com/tuttleofx/TuttleOFX/blob/develop/INSTALL.md#additionnal-dependencies-for-sam).
Did you try this?
```
sam --help
```

More help [here](https://github.com/tuttleofx/TuttleOFX/blob/develop/USAGE.md).

**Comment by Eiken** [comment]
Ahhh, I just grabbed it from the website which I see now have a an old version.

The one from github releases worked a lot better. Everything seems to work fine except for avwriter.

I setup my environment as:
export TUTTLE_ROOT=/path/to/tuttle
export OFX_PLUGIN_PATH=$OFX_PLUGIN_PATH:$TUTTLE_ROOT/OFX
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TUTTLE_ROOT/lib
export PYTHONPATH=$PYTHONPATH:$TUTTLE_ROOT/bin/python
export PYTHONPATH=$PYTHONPATH:$TUTTLE_ROOT/lib/python2.7/site-packages
export PATH=$PATH:$TUTTLE_ROOT/bin

Guess I have missed something that is needed for sam do find avtranscoder

**Comment by cchampet** [comment]
Great news! avtranscoder library should be in $TUTTLE_ROOT/lib, like other libraries.
Maybe your problem is a missing dependency to load avtranscoder. Could you check this:
```
ldd $TUTTLE_ROOT/lib/libavtranscoder.so
```

**Comment by Eiken** [comment]
libbz2.so.1.0 => not found
That was the culprit. On Centos it looked like:
lrwxrwxrwx    1 root root       11 Mar 30 14:03 libbz2.so -> libbz2.so.1
lrwxrwxrwx    1 root root       15 Feb  2 17:31 libbz2.so.1 -> libbz2.so.1.0.6
-rwxr-xr-x    1 root root    68192 Nov 20 06:04 libbz2.so.1.0.6

Added another symlink and it works.

Thanks for the help

**Comment by cchampet** [comment]
Ok, thanks for your feedback.

**Comment by Eiken** [comment]
This is a super great project btw!

**Comment by cchampet** [comment]
Thank you for your feedback! :)
I keep this issue open to not forget to add libbz2 to the list of libraries deployed by Travis.
TODO: add this [line](https://github.com/avTranscoder/avTranscoder/blob/develop/.travis.yml#L119) to the Travis configuration file of Tuttle.
