### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by brothermechanic** [tuttleofx/TuttleOFX#561]
Hello
I want to try last git version (i haved worked version several month ago), but get this error
 https://bpaste.net/show/7300f93b1e9c

My system 
gentoo amd64
python 2.7 and 3.5,
boost-1.61
https://bpaste.net/show/922d981558ba

**Comment by cchampet** [comment]
Hello!
It seems that the AudioVideo plugin failed to compile. And this plugin depends on a git submodule called avTranscoder. Are you sure that your submodule is up to data since your last pull?

```
git submodule update -i
```

**Comment by brothermechanic** [comment]
Hello
yes, because i compiled it from scratch

**Comment by cchampet** [comment]
Okey so you did:

```
git clone --recursive git://github.com/tuttleofx/TuttleOFX.git
```

**Comment by brothermechanic** [comment]
I do this
git clone git://github.com/tuttleofx/TuttleOFX.git
git submodule update -i --recursive
...
This is the same, isn't it?

**Comment by cchampet** [comment]
Yes this is the same, you have done right. The problem is somewhere else... Did you succeed to compile an older Tuttle version with boost-1.61? I am used to compile with boost-1.55.

By the way, I don't know if it suits you but you have the tuttle binaries of latest versions [here](https://github.com/tuttleofx/TuttleOFX/releases).

**Comment by cchampet** [comment]
Feel free to reopen it if needed.
